[package]
name = "rrctrl"
version = "0.3.2"
edition = "2021"
description = "Automatically change monitor refresh rate when specific applications are running"
repository = "https://github.com/AmionSky/rrctrl"
readme = "README.md"
license = "GPL-3.0-only"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
notify = "5.0.0-pre.14"
crossbeam-utils = "0.8"

[dependencies.windows]
version = "0.35.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading"
]

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"
