[package]
name = "rrctrl"
version = "0.3.4"
edition = "2021"
description = "Automatically change monitor refresh rate when specific applications are running"
repository = "https://github.com/AmionSky/rrctrl"
readme = "README.md"
license = "GPL-3.0-only"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
notify = "5.0.0"
crossbeam-utils = "0.8"

[dependencies.windows]
#version = "0.43.0"
git = "https://github.com/microsoft/windows-rs"
rev = "1bfd409a449656f2eb1362e9fa7ccdbe52e5e6d9"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading"
]

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
panic = "abort"
