[package]
name = "rrctrl"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    "bindings",
]

[dependencies]
bindings = { path = "bindings" }
windows = "0.21.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
notify = "5.0.0-pre.13"
crossbeam-utils = "0.8"

[profile.release]
opt-level = 3
overflow-checks = false
lto = "fat"
panic = "abort"
codegen-units = 1