[package]
name = "rrctrl"
version = "0.2.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
notify = "5.0.0-pre.13"
crossbeam-utils = "0.8"

[dependencies.windows]
version = "0.26.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading"
]

[profile.release]
opt-level = 3
overflow-checks = false
lto = "fat"
panic = "abort"
codegen-units = 1