[package]
name = "rrctrl-config"
version = "0.1.0"
edition = "2021"
description = "RRCtrl configuration schema"
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
serde = { version = "1.0.0", features = ["derive"] }