import { Button, ScrollView, LineEdit, Palette } from "std-widgets.slint";

export component ApplicationsSettings inherits VerticalLayout {
    in-out property<bool> modified: false;
    in-out property<[string]> apps;

    spacing: 8px;

    Rectangle {
        background: Palette.color-scheme == ColorScheme.dark
            ? Palette.background.darker(0.2)
            : Palette.background.brighter(0.2);

        ScrollView {
            VerticalLayout {
                for data in apps : TouchArea {
                    Rectangle {
                        states [
                            hovered when parent.has-hover : {
                                background: Palette.color-scheme == ColorScheme.dark
                                    ? Palette.background.brighter(0.2)
                                    : Palette.background.darker(0.2);
                            }
                        ]
                        HorizontalLayout {
                            padding-top: 2px;
                            padding-bottom: 2px;
                            padding-left: 8px;
                            padding-right: 2px;

                            Text {
                                horizontal-stretch: 1;
                                vertical-alignment: center;
                                text: data;
                            }
                            Button {
                                horizontal-stretch: 0;
                                icon: Palette.color-scheme == ColorScheme.dark
                                 ? @image-url("../../../assets/close-light.svg")
                                 : @image-url("../../../assets/close-dark.svg");
                                clicked => {
                                    
                                }
                            }
                        }
                    }
                } 
            }
        }
    }
    HorizontalLayout {
        spacing: 4px;
        LineEdit {}
        Button {
            text: "Add";
            clicked => {
                root.modified = true;
            }
        }
    }
}